//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maitonn.Web
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public abstract class Category
    {
        public Category()
        {

        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [MaxLength(50)]
        public string CateName { get; set; }

        public int? PID { get; set; }

        public int Length { get; set; }

        public int OrderIndex { get; set; }

        [ScriptIgnore]
        public virtual Category PCategory { get; set; }

        [ScriptIgnore]
        public virtual ICollection<Category> ChildCategoies { get; set; }


    }
}
