//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maitonn.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Member_Money_List
    {

        public Member_Money_List()
        {
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [MaxLength(4)]
        public string Key { get; set; }

        public int MemberID { get; set; }

        public int Money { get; set; }

        public int RelateID { get; set; }

        public DateTime AddTime { get; set; }

        [MaxLength(250)]
        public string Description { get; set; }

    }
}
