//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maitonn.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Member_Profile
    {

        public Member_Profile()
        {
            this.Borthday = DateTime.Now;
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Key]
        public int MemberID { get; set; }

        public bool Sex { get; set; }

        public System.DateTime Borthday { get; set; }

        public int CityCode { get; set; }

        [MaxLength(20)]
        public string RealName { get; set; }

        [MaxLength(20)]
        public string Mobile { get; set; }

        [MaxLength(20)]
        public string Phone { get; set; }

        [MaxLength(20)]
        public string QQ { get; set; }

        [MaxLength(50)]
        public string MSN { get; set; }

        [MaxLength(50)]
        public string Address { get; set; }

        public double Lat { get; set; }

        public double Lng { get; set; }

        [MaxLength(150)]
        public string Description { get; set; }

        public DateTime VipStartTime { get; set; }

        public DateTime VipEndTime { get; set; }

        public int VipLevel { get; set; }

        public virtual Area Area { get; set; }

        public virtual Member Member { get; set; }
    }
}
