//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maitonn.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Member_CreditIndex_Type
    {

        public Member_CreditIndex_Type()
        {
        }

        [Key]
        [MaxLength(4)]
        [Display(Name = "类型代码")]
        public string Key { get; set; }

        [Display(Name = "消费额度")]
        public int CreditIndex { get; set; }

        [Display(Name = "次数上限")]
        public int TimeLimit { get; set; }

        [Display(Name = "每日消费次数上线")]
        public int DayLimit { get; set; }

        [Display(Name = "额度总数上线")]
        public int CreditIndexLimit { get; set; }

        [MaxLength(50)]
        [Display(Name = "类型描述")]
        public string Name { get; set; }

    }
}
