//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maitonn.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Member_CreditIndex
    {

        public Member_CreditIndex()
        {

        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Key]
        public int MemberID { get; set; }

        public int TotalCreditIndex { get; set; }

        public int CreditIndex00 { get; set; }

        public int CreditIndex01 { get; set; }

        public int CreditIndex02 { get; set; }

        public int CreditIndex03 { get; set; }

        public int CreditIndex04 { get; set; }

        public int CreditIndex05 { get; set; }

        public int CreditIndex06 { get; set; }

        public int CreditIndex07 { get; set; }

        public int CreditIndex08 { get; set; }

        public int CreditIndex09 { get; set; }

        public virtual Member Member { get; set; }
    }
}
