//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maitonn.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Member_Money
    {

        public Member_Money()
        {
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Key]
        public int MemberID { get; set; }

        public int TotalMoney { get; set; }

        public int Money00 { get; set; }

        public int Money01 { get; set; }

        public int Money02 { get; set; }

        public int Money03 { get; set; }

        public int Money04 { get; set; }

        public int Money05 { get; set; }

        public int Money06 { get; set; }

        public int Money07 { get; set; }

        public int Money08 { get; set; }

        public int Money09 { get; set; }

        public virtual Member Member { get; set; }
    }
}
