// <auto-generated />
namespace Maitonn.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AlertServerItemAddTopType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlertServerItemAddTopType));
        
        string IMigrationMetadata.Id
        {
            get { return "201304280716127_AlertServerItemAddTopType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
