// <auto-generated />
namespace Maitonn.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddMedia_refresh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMedia_refresh));
        
        string IMigrationMetadata.Id
        {
            get { return "201305020925110_AddMedia_refresh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
